import type { Exercise } from '../types';

/* -------------------------------------------------------------------------- */
/*  Seed exercise list — spec §8. This is the entire universe of exercises;   */
/*  it is the fixed equipment in the garage, not a catalogue to search.       */
/*                                                                            */
/*  gripLoad drives the golf rule (Phase 3): grip, lat and forearm work must  */
/*  not land within 3 days of a round. 'high' items are the golf-sensitive     */
/*  ones called out in the spec; 'low' is my own conservative marking for     */
/*  movements that load the forearm flexors as a secondary, which still adds  */
/*  up across a week.                                                        */
/*                                                                            */
/*  freeDbId is hand-mapped, never fuzzy-matched (§9), and every value is      */
/*  checked against a snapshot of the upstream id list by the seed test —      */
/*  a wrong id fails silently otherwise, which is exactly the failure mode     */
/*  §9 warns about. That check caught two bad guesses on its first run.        */
/*                                                                            */
/*  §9 predicts nothing upstream matches "Smith machine squat with an 18 kg    */
/*  bar". The data says otherwise: there is a full Smith_Machine_* family, so  */
/*  the Smith station is mapped after all.                                     */
/*                                                                            */
/*  An audit of all 876 upstream records settled the rest. Three were only     */
/*  ever a naming difference — the low-to-high lift is Standing_Cable_Lift,    */
/*  the band lateral walk is Monster_Walk, the dip-station knee raise is       */
/*  Knee_Hip_Raise_On_Parallel_Bars.                                          */
/*                                                                            */
/*  Two more take a record of the same movement on a different implement —     */
/*  the triceps kickback and the landmine press. That is allowed because the   */
/*  detail sheet labels the block "Reference", prints the upstream name and    */
/*  says the cue wins where they disagree, so a dumbbell photo of a kickback   */
/*  still shows the arm action without claiming to be this rack.               */
/*                                                                            */
/*  Two things are refused. A record for a different MOVEMENT, however well    */
/*  the name fits: upstream's cable kickback is a glute exercise and ours is   */
/*  triceps, so ours takes the dumbbell record instead. And a record already   */
/*  spoken for — four near-matches were dropped for this, because sharing      */
/*  Pullups between the pull-up and the neutral-grip pull-up puts one photo    */
/*  and one name on two exercises that exist precisely because they differ.    */
/*                                                                            */
/*  The eleven left have no upstream record worth showing, and no licensable   */
/*  photo exists for them anywhere. They carry STEPS in cues.ts instead —      */
/*  our own words, about this rack, needing no network.                        */
/* -------------------------------------------------------------------------- */

/** Cable ratios, spec §2. The single most important numbers in the app. */
export const CABLE_SINGLE_PULLEY = 0.49;
export const CABLE_BILATERAL = 0.98;
export const CABLE_DUAL_ADAPTOR = 1.0;

/** Bar weights, spec §2. */
export const FREE_BAR_KG = 20;
export const SMITH_BAR_KG = 18;

/** One functional-trainer stack, spec §2 (13 × 5 kg plates + 5 kg selector rod). */
export const CABLE_STACK_KG = 70;

export const EXERCISES: Exercise[] = [
  /* --- Free bar (20 kg, ×1.0) -------------------------------------------- */
  {
    id: 'bb_back_squat',
    freeDbId: 'Barbell_Squat',
    name: 'Back squat',
    station: 'free_bar',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'lower_back', 'abs'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 12,
    restSeconds: 180,
    skillLevel: 'intermediate',
    pattern: 'squat',
    spinalLoad: 'high',
  },
  {
    id: 'bb_front_squat',
    freeDbId: 'Front_Barbell_Squat',
    name: 'Front squat',
    station: 'free_bar',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'upper_back', 'abs', 'lower_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 10,
    restSeconds: 180,
    skillLevel: 'intermediate',
    pattern: 'squat',
    spinalLoad: 'high',
  },
  {
    id: 'bb_rdl',
    freeDbId: 'Romanian_Deadlift',
    name: 'Romanian deadlift',
    station: 'free_bar',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'lats', 'traps', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 12,
    restSeconds: 180,
    skillLevel: 'intermediate',
    pattern: 'hinge',
    spinalLoad: 'high',
  },
  {
    id: 'bb_deadlift',
    freeDbId: 'Barbell_Deadlift',
    name: 'Conventional deadlift',
    station: 'free_bar',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['quads', 'lower_back', 'lats', 'traps', 'upper_back', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 3,
    repMax: 8,
    restSeconds: 180,
    skillLevel: 'advanced',
    pattern: 'hinge',
    spinalLoad: 'high',
  },
  {
    id: 'bb_bench_press',
    freeDbId: 'Barbell_Bench_Press_-_Medium_Grip',
    name: 'Bench press',
    station: 'free_bar',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'push_h',
    spinalLoad: 'low',
  },
  {
    id: 'bb_overhead_press',
    freeDbId: 'Standing_Military_Press',
    name: 'Overhead press',
    station: 'free_bar',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['side_delts', 'triceps', 'abs', 'upper_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 10,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'push_v',
    spinalLoad: 'low',
  },
  {
    id: 'bb_bent_over_row',
    freeDbId: 'Bent_Over_Barbell_Row',
    name: 'Bent-over row',
    station: 'free_bar',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms', 'lower_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'pull_h',
    spinalLoad: 'high',
  },
  {
    id: 'bb_curl',
    freeDbId: 'Barbell_Curl',
    name: 'Barbell curl',
    station: 'free_bar',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'low',
  },

  /* --- Smith (18 kg, ×1.0) ----------------------------------------------- */
  {
    id: 'sm_squat',
    freeDbId: 'Smith_Machine_Squat',
    name: 'Smith squat',
    station: 'smith',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 180,
    skillLevel: 'beginner',
    pattern: 'squat',
    spinalLoad: 'high',
  },
  {
    id: 'sm_bench_press',
    freeDbId: 'Smith_Machine_Bench_Press',
    name: 'Smith bench press',
    station: 'smith',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'push_h',
    spinalLoad: 'low',
  },
  {
    id: 'sm_incline_press',
    freeDbId: 'Smith_Machine_Incline_Bench_Press',
    name: 'Smith incline press',
    station: 'smith',
    primaryMuscles: ['chest', 'front_delts'],
    secondaryMuscles: ['triceps'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'push_h',
    spinalLoad: 'low',
  },
  {
    id: 'sm_overhead_press',
    freeDbId: 'Smith_Machine_Overhead_Shoulder_Press',
    name: 'Smith overhead press',
    station: 'smith',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['side_delts', 'triceps', 'upper_back'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'push_v',
    spinalLoad: 'low',
  },
  {
    id: 'sm_shrug',
    freeDbId: 'Barbell_Shrug',
    name: 'Smith shrug',
    station: 'smith',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['upper_back', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 90,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'low',
  },
  {
    id: 'sm_calf_raise',
    freeDbId: 'Smith_Machine_Calf_Raise',
    name: 'Smith calf raise',
    station: 'smith',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'squat',
    spinalLoad: 'none',
  },

  /* --- Cable, single pulley (×0.49) -------------------------------------- */
  {
    id: 'cb_chop',
    freeDbId: 'Standing_Cable_Wood_Chop',
    name: 'Chop (high→low)',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'front_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'cb_lift',
    freeDbId: 'Standing_Cable_Lift',
    name: 'Lift (low→high)',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'front_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'cb_pallof_press',
    freeDbId: 'Pallof_Press',
    name: 'Pallof press',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques', 'abs'],
    secondaryMuscles: ['front_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'core',
    spinalLoad: 'none',
  },
  {
    id: 'cb_single_arm_row',
    freeDbId: 'Seated_One-arm_Cable_Pulley_Rows',
    name: 'Single-arm cable row',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 90,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'low',
  },
  {
    id: 'cb_tricep_pushdown',
    freeDbId: 'Triceps_Pushdown',
    name: 'Tricep pushdown',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'push_h',
    spinalLoad: 'none',
  },
  {
    id: 'cb_bicep_curl',
    freeDbId: 'Standing_Biceps_Cable_Curl',
    name: 'Bicep curl (cable)',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'none',
  },
  {
    id: 'cb_lateral_raise',
    freeDbId: 'Cable_Seated_Lateral_Raise',
    name: 'Lateral raise (cable)',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: ['traps'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'push_v',
    spinalLoad: 'none',
  },
  {
    id: 'cb_face_pull',
    freeDbId: 'Face_Pull',
    name: 'Face pull',
    station: 'cable',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back', 'traps', 'biceps'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'none',
  },
  {
    id: 'cb_kickback',
    freeDbId: 'Tricep_Dumbbell_Kickback',
    name: 'Cable kickback',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'push_h',
    spinalLoad: 'none',
  },

  /* --- Cable, bilateral / dual adaptor (×0.98 / ×1.0) -------------------- */
  {
    id: 'cb_lat_pulldown',
    freeDbId: 'Wide-Grip_Lat_Pulldown',
    name: 'Lat pulldown',
    station: 'cable',
    attachment: 'lat_pulldown_bar',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upper_back', 'biceps', 'rear_delts', 'forearms'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'pull_v',
    spinalLoad: 'low',
  },
  {
    id: 'cb_seated_row',
    freeDbId: 'Seated_Cable_Rows',
    name: 'Seated row',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'low',
  },
  {
    id: 'cb_fly',
    freeDbId: 'Cable_Crossover',
    name: 'Cable fly',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'push_h',
    spinalLoad: 'none',
  },
  {
    id: 'cb_straight_arm_pulldown',
    freeDbId: 'Straight-Arm_Pulldown',
    name: 'Straight-arm pulldown',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps', 'abs'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'pull_v',
    spinalLoad: 'none',
  },

  /* --- Landmine ---------------------------------------------------------- */
  /* The landmine loads the 20 kg Olympic bar, so barWeight is 20. Its lever
     geometry means the load at the handle is lower than the bar+plate total;
     that is not modelled in v1 and is worth revisiting if the numbers start
     looking odd next to the free-bar lifts. */
  {
    id: 'lm_press',
    freeDbId: 'Landmine_Linear_Jammer',
    name: 'Landmine press',
    station: 'landmine',
    attachment: 'landmine_handle',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['chest', 'triceps', 'abs'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'push_v',
    spinalLoad: 'low',
  },
  {
    id: 'lm_row',
    freeDbId: 'T-Bar_Row_with_Handle',
    name: 'Landmine row',
    station: 'landmine',
    attachment: 'landmine_handle',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'high',
  },
  {
    id: 'lm_rotation',
    freeDbId: 'Landmine_180s',
    name: 'Landmine rotation',
    station: 'landmine',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'front_delts'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 90,
    skillLevel: 'intermediate',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'lm_squat_to_press',
    name: 'Landmine squat-to-press',
    station: 'landmine',
    primaryMuscles: ['quads', 'glutes', 'front_delts'],
    secondaryMuscles: ['abs', 'triceps', 'upper_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 10,
    restSeconds: 120,
    skillLevel: 'advanced',
    pattern: 'squat',
    spinalLoad: 'low',
  },

  /* --- Kettlebell -------------------------------------------------------- */
  {
    id: 'kb_swing',
    freeDbId: 'One-Arm_Kettlebell_Swings',
    name: 'Swing',
    station: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'lats', 'traps', 'forearms', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 90,
    skillLevel: 'intermediate',
    pattern: 'hinge',
    spinalLoad: 'low',
  },
  {
    id: 'kb_goblet_squat',
    freeDbId: 'Goblet_Squat',
    name: 'Goblet squat',
    station: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs', 'upper_back', 'adductors'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 15,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'squat',
    spinalLoad: 'low',
  },
  {
    id: 'kb_single_leg_rdl',
    freeDbId: 'Kettlebell_One-Legged_Deadlift',
    name: 'Single-leg RDL',
    station: 'kettlebell',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'abs', 'obliques', 'forearms'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 90,
    skillLevel: 'intermediate',
    pattern: 'hinge',
    spinalLoad: 'low',
  },
  {
    id: 'kb_turkish_get_up',
    freeDbId: 'Kettlebell_Turkish_Get-Up_Squat_style',
    name: 'Turkish get-up',
    station: 'kettlebell',
    primaryMuscles: ['abs', 'front_delts'],
    secondaryMuscles: ['obliques', 'glutes', 'triceps', 'quads'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 1,
    repMax: 5,
    restSeconds: 180,
    skillLevel: 'advanced',
    pattern: 'core',
    spinalLoad: 'low',
  },
  {
    id: 'kb_suitcase_carry',
    freeDbId: 'Farmers_Walk',
    name: 'Suitcase carry',
    station: 'kettlebell',
    primaryMuscles: ['forearms', 'obliques'],
    secondaryMuscles: ['traps', 'abs', 'glutes'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 20,
    repMax: 90,
    repUnit: 'seconds',
    restSeconds: 90,
    skillLevel: 'beginner',
    pattern: 'carry',
    spinalLoad: 'low',
  },

  /* --- Bodyweight -------------------------------------------------------- */
  {
    id: 'bw_pull_up',
    freeDbId: 'Pullups',
    name: 'Pull-up',
    station: 'bodyweight',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upper_back', 'biceps', 'forearms', 'rear_delts', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 3,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'pull_v',
    spinalLoad: 'low',
  },
  {
    id: 'bw_chin_up',
    freeDbId: 'Chin-Up',
    name: 'Chin-up',
    station: 'bodyweight',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upper_back', 'forearms', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 3,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'pull_v',
    spinalLoad: 'low',
  },
  {
    id: 'bw_dip',
    freeDbId: 'Dips_-_Triceps_Version',
    name: 'Dip',
    station: 'bodyweight',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['front_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 15,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'push_v',
    spinalLoad: 'low',
  },
  {
    id: 'bw_push_up',
    freeDbId: 'Pushups',
    name: 'Push-up',
    station: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 25,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'push_h',
    spinalLoad: 'none',
  },
  {
    id: 'bw_plank',
    freeDbId: 'Plank',
    name: 'Plank',
    station: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'front_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 20,
    repMax: 120,
    repUnit: 'seconds',
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'core',
    spinalLoad: 'none',
  },
  {
    id: 'bw_side_plank',
    freeDbId: 'Side_Bridge',
    name: 'Side plank',
    station: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'side_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 20,
    repMax: 90,
    repUnit: 'seconds',
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'core',
    spinalLoad: 'none',
  },
  {
    id: 'bw_hanging_leg_raise',
    freeDbId: 'Hanging_Leg_Raise',
    name: 'Hanging leg raise',
    station: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'forearms', 'lats'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 15,
    restSeconds: 90,
    skillLevel: 'intermediate',
    pattern: 'core',
    spinalLoad: 'low',
  },
  {
    id: 'bw_split_squat',
    freeDbId: 'Split_Squats',
    name: 'Split squat',
    station: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 15,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'squat',
    spinalLoad: 'low',
  },
  {
    id: 'bw_glute_bridge',
    freeDbId: 'Butt_Lift_Bridge',
    name: 'Glute bridge',
    station: 'bodyweight',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'hinge',
    spinalLoad: 'low',
  },

  /* --- Bands (rpe_only — load is not quantifiable) ----------------------- */
  {
    id: 'bd_pull_apart',
    freeDbId: 'Band_Pull_Apart',
    name: 'Band pull-apart',
    station: 'band',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back', 'traps'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 12,
    repMax: 25,
    restSeconds: 45,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'none',
  },
  {
    id: 'bd_external_rotation',
    freeDbId: 'External_Rotation_with_Band',
    name: 'Band external rotation',
    station: 'band',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['side_delts'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 12,
    repMax: 20,
    restSeconds: 45,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'none',
  },
  {
    id: 'bd_pull_through',
    freeDbId: 'Band_Good_Morning_Pull_Through',
    name: 'Band pull-through',
    station: 'band',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 12,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'hinge',
    spinalLoad: 'none',
  },
  {
    id: 'bd_lateral_walk',
    freeDbId: 'Monster_Walk',
    name: 'Band lateral walk',
    station: 'band',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['adductors', 'quads'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 45,
    skillLevel: 'beginner',
    pattern: 'carry',
    spinalLoad: 'none',
  },

  /* --- Rotational and golf power ----------------------------------------- */
  /* The swing is hips then torso. Nothing in the original seed trained that
     sequence, which is the one thing this app exists to protect. */
  {
    id: 'lm_rotational_press',
    name: 'Landmine rotational press',
    station: 'landmine',
    attachment: 'landmine_handle',
    primaryMuscles: ['front_delts', 'obliques'],
    secondaryMuscles: ['triceps', 'abs', 'glutes'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 10,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'lm_scoop',
    name: 'Landmine scoop toss',
    station: 'landmine',
    attachment: 'landmine_handle',
    primaryMuscles: ['obliques', 'glutes'],
    secondaryMuscles: ['abs', 'front_delts', 'quads'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: true,
    isMobility: false,
    repMin: 5,
    repMax: 8,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'cb_rotational_row',
    name: 'Cable row with rotation',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['upper_back', 'obliques'],
    secondaryMuscles: ['lats', 'biceps', 'abs', 'rear_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 12,
    restSeconds: 90,
    skillLevel: 'intermediate',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'cb_pallof_rotation',
    freeDbId: 'Pallof_Press_With_Rotation',
    name: 'Pallof press-out to rotation',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques', 'abs'],
    secondaryMuscles: ['front_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 12,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'cb_punch',
    name: 'Standing cable punch',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['chest', 'front_delts', 'abs'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 15,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'kb_russian_twist',
    freeDbId: 'Russian_Twist',
    name: 'Kettlebell Russian twist',
    station: 'kettlebell',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'forearms'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'low',
  },
  {
    id: 'bw_side_plank_reach',
    name: 'Side plank with reach-through',
    station: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'side_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 45,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'low',
  },

  /* --- Explosive. Ordered first in a session by isExplosive: power work is
     worthless once fatigued, the same reason hinges lead. ----------------- */
  {
    id: 'kb_clean',
    freeDbId: 'Kettlebell_Hang_Clean',
    name: 'Kettlebell clean',
    station: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['traps', 'forearms', 'upper_back', 'quads'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
    isExplosive: true,
    isMobility: false,
    repMin: 5,
    repMax: 10,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'hinge',
    spinalLoad: 'low',
  },
  {
    id: 'kb_high_pull',
    freeDbId: 'Kettlebell_Sumo_High_Pull',
    name: 'Kettlebell high pull',
    station: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings', 'traps'],
    secondaryMuscles: ['upper_back', 'rear_delts', 'forearms'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
    isExplosive: true,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'hinge',
    spinalLoad: 'low',
  },
  {
    id: 'sm_push_press',
    freeDbId: 'Push_Press',
    name: 'Smith push press',
    station: 'smith',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['triceps', 'side_delts', 'quads', 'upper_back'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: true,
    isMobility: false,
    repMin: 3,
    repMax: 8,
    restSeconds: 150,
    skillLevel: 'intermediate',
    pattern: 'push_v',
    spinalLoad: 'low',
  },
  {
    id: 'bw_jump_squat',
    freeDbId: 'Freehand_Jump_Squat',
    name: 'Jump squat',
    station: 'bodyweight',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'hamstrings'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: true,
    isMobility: false,
    repMin: 5,
    repMax: 10,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'squat',
    spinalLoad: 'low',
  },

  /* --- Staples the equipment already supported ---------------------------- */
  /* sm_inverted_row is the only horizontal pull here that is not grip-heavy,
     and bw_captains_knee_raise is the hanging leg raise without the hang.
     Both exist so a session near a round still has something to reach for. */
  {
    id: 'bb_hip_thrust',
    freeDbId: 'Barbell_Hip_Thrust',
    name: 'Barbell hip thrust',
    station: 'free_bar',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 120,
    skillLevel: 'beginner',
    pattern: 'hinge',
    spinalLoad: 'low',
  },
  {
    id: 'kb_bulgarian_split',
    name: 'Bulgarian split squat',
    station: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'squat',
    spinalLoad: 'low',
  },
  {
    id: 'sm_rdl',
    freeDbId: 'Smith_Machine_Stiff-Legged_Deadlift',
    name: 'Smith RDL',
    station: 'smith',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'traps', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 12,
    restSeconds: 150,
    skillLevel: 'beginner',
    pattern: 'hinge',
    spinalLoad: 'high',
  },
  {
    id: 'sm_inverted_row',
    freeDbId: 'Inverted_Row',
    name: 'Inverted row',
    station: 'smith',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 6,
    repMax: 15,
    restSeconds: 90,
    skillLevel: 'beginner',
    pattern: 'pull_h',
    spinalLoad: 'none',
  },
  {
    id: 'cb_pull_through',
    freeDbId: 'Pull_Through',
    name: 'Cable pull-through',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'abs'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: true,
    isExplosive: false,
    isMobility: false,
    repMin: 10,
    repMax: 20,
    restSeconds: 90,
    skillLevel: 'beginner',
    pattern: 'hinge',
    spinalLoad: 'low',
  },
  {
    id: 'kb_reverse_lunge',
    freeDbId: 'Dumbbell_Rear_Lunge',
    name: 'Reverse lunge',
    station: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 90,
    skillLevel: 'beginner',
    pattern: 'squat',
    spinalLoad: 'low',
  },
  {
    id: 'kb_step_up',
    freeDbId: 'Dumbbell_Step_Ups',
    name: 'Step-up',
    station: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 15,
    restSeconds: 90,
    skillLevel: 'beginner',
    pattern: 'squat',
    spinalLoad: 'low',
  },
  {
    id: 'bw_ab_wheel',
    freeDbId: 'Ab_Roller',
    name: 'Ab wheel rollout',
    station: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'lats', 'lower_back'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'low',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 5,
    repMax: 15,
    restSeconds: 60,
    skillLevel: 'intermediate',
    pattern: 'core',
    spinalLoad: 'low',
  },
  {
    id: 'bw_neutral_pull_up',
    name: 'Neutral-grip pull-up',
    station: 'bodyweight',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'forearms', 'rear_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 3,
    repMax: 12,
    restSeconds: 120,
    skillLevel: 'intermediate',
    pattern: 'pull_v',
    spinalLoad: 'low',
  },
  {
    id: 'bw_captains_knee_raise',
    freeDbId: 'Knee_Hip_Raise_On_Parallel_Bars',
    name: 'Knee raise (dip station)',
    station: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'front_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 8,
    repMax: 20,
    restSeconds: 60,
    skillLevel: 'beginner',
    pattern: 'core',
    spinalLoad: 'none',
  },
  {
    id: 'kb_overhead_carry',
    name: 'Single-arm overhead carry',
    station: 'kettlebell',
    primaryMuscles: ['side_delts', 'obliques'],
    secondaryMuscles: ['abs', 'traps', 'forearms'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
    isExplosive: false,
    isMobility: false,
    repMin: 20,
    repMax: 60,
    repUnit: 'seconds',
    restSeconds: 90,
    skillLevel: 'intermediate',
    pattern: 'carry',
    spinalLoad: 'low',
  },

  /* --- Mobility. Warm-up movements: never programmed as working sets and
     never counted in weekly volume. Thoracic and hip rotation are the two
     restrictions that shorten a backswing. -------------------------------- */
  {
    id: 'mb_open_book',
    name: 'Open book thoracic rotation',
    station: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['upper_back', 'chest'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: true,
    repMin: 8,
    repMax: 12,
    restSeconds: 30,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'none',
  },
  {
    id: 'mb_90_90',
    name: '90/90 hip switch',
    station: 'bodyweight',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['adductors', 'obliques'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: false,
    isExplosive: false,
    isMobility: true,
    repMin: 8,
    repMax: 12,
    restSeconds: 30,
    skillLevel: 'beginner',
    pattern: 'rotation',
    spinalLoad: 'none',
  },
];

export const STATION_LABEL: Record<Exercise['station'], string> = {
  free_bar: 'Free bar',
  smith: 'Smith',
  cable: 'Cable',
  kettlebell: 'Kettlebell',
  bodyweight: 'Bodyweight',
  band: 'Band',
  landmine: 'Landmine',
};

/** Order stations the way the seed list is grouped, spec §8. */
export const STATION_ORDER: Exercise['station'][] = [
  'free_bar',
  'smith',
  'cable',
  'landmine',
  'kettlebell',
  'bodyweight',
  'band',
];
