import type { Exercise } from '../types';

/* -------------------------------------------------------------------------- */
/*  Seed exercise list — spec §8. This is the entire universe of exercises;   */
/*  it is the fixed equipment in the garage, not a catalogue to search.       */
/*                                                                            */
/*  gripLoad drives the golf rule (Phase 3): grip, lat and forearm work must  */
/*  not land within 3 days of a round. 'high' items are the golf-sensitive     */
/*  ones called out in the spec; 'low' is my own conservative marking for     */
/*  movements that load the forearm flexors as a secondary, which still adds  */
/*  up across a week.                                                        */
/*                                                                            */
/*  freeDbId is hand-mapped, never fuzzy-matched (§9). Nulls are expected and */
/*  fine — nothing in free-exercise-db matches "Smith machine squat with an    */
/*  18 kg bar", so the whole Smith station is null, as are the landmine and    */
/*  band movements. Where I could not be certain of the upstream record id I   */
/*  left it undefined rather than guess: a wrong id fails silently, which is   */
/*  exactly the failure mode §9 warns about.                                  */
/* -------------------------------------------------------------------------- */

/** Cable ratios, spec §2. The single most important numbers in the app. */
export const CABLE_SINGLE_PULLEY = 0.49;
export const CABLE_BILATERAL = 0.98;
export const CABLE_DUAL_ADAPTOR = 1.0;

/** Bar weights, spec §2. */
export const FREE_BAR_KG = 20;
export const SMITH_BAR_KG = 18;

/** One functional-trainer stack, spec §2 (13 × 5 kg plates + 5 kg selector rod). */
export const CABLE_STACK_KG = 70;

export const EXERCISES: Exercise[] = [
  /* --- Free bar (20 kg, ×1.0) -------------------------------------------- */
  {
    id: 'bb_back_squat',
    freeDbId: 'Barbell_Squat',
    name: 'Back squat',
    station: 'free_bar',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'lower_back', 'abs'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bb_front_squat',
    freeDbId: 'Front_Barbell_Squat',
    name: 'Front squat',
    station: 'free_bar',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'upper_back', 'abs', 'lower_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bb_rdl',
    freeDbId: 'Romanian_Deadlift',
    name: 'Romanian deadlift',
    station: 'free_bar',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'lats', 'traps', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
  },
  {
    id: 'bb_deadlift',
    freeDbId: 'Barbell_Deadlift',
    name: 'Conventional deadlift',
    station: 'free_bar',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['quads', 'lower_back', 'lats', 'traps', 'upper_back', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
  },
  {
    id: 'bb_bench_press',
    freeDbId: 'Barbell_Bench_Press_-_Medium_Grip',
    name: 'Bench press',
    station: 'free_bar',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bb_overhead_press',
    freeDbId: 'Standing_Military_Press',
    name: 'Overhead press',
    station: 'free_bar',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['side_delts', 'triceps', 'abs', 'upper_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bb_bent_over_row',
    freeDbId: 'Bent_Over_Barbell_Row',
    name: 'Bent-over row',
    station: 'free_bar',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms', 'lower_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'bb_curl',
    freeDbId: 'Barbell_Curl',
    name: 'Barbell curl',
    station: 'free_bar',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
  },

  /* --- Smith (18 kg, ×1.0) ----------------------------------------------- */
  {
    id: 'sm_squat',
    name: 'Smith squat',
    station: 'smith',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'sm_bench_press',
    name: 'Smith bench press',
    station: 'smith',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'sm_incline_press',
    name: 'Smith incline press',
    station: 'smith',
    primaryMuscles: ['chest', 'front_delts'],
    secondaryMuscles: ['triceps'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'sm_overhead_press',
    name: 'Smith overhead press',
    station: 'smith',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['side_delts', 'triceps', 'upper_back'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'sm_shrug',
    name: 'Smith shrug',
    station: 'smith',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['upper_back', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'sm_calf_raise',
    name: 'Smith calf raise',
    station: 'smith',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    loadMultiplier: 1.0,
    barWeight: SMITH_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },

  /* --- Cable, single pulley (×0.49) -------------------------------------- */
  {
    id: 'cb_chop',
    name: 'Chop (high→low)',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'front_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'cb_lift',
    name: 'Lift (low→high)',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'front_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'cb_pallof_press',
    name: 'Pallof press',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['obliques', 'abs'],
    secondaryMuscles: ['front_delts'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'cb_single_arm_row',
    freeDbId: 'Seated_One-arm_Cable_Pulley_Rows',
    name: 'Single-arm cable row',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
  },
  {
    id: 'cb_tricep_pushdown',
    freeDbId: 'Triceps_Pushdown',
    name: 'Tricep pushdown',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'cb_bicep_curl',
    name: 'Bicep curl (cable)',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
  },
  {
    id: 'cb_lateral_raise',
    name: 'Lateral raise (cable)',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: ['traps'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'cb_face_pull',
    freeDbId: 'Face_Pull',
    name: 'Face pull',
    station: 'cable',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back', 'traps', 'biceps'],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'cb_kickback',
    name: 'Cable kickback',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    loadMultiplier: CABLE_SINGLE_PULLEY,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },

  /* --- Cable, bilateral / dual adaptor (×0.98 / ×1.0) -------------------- */
  {
    id: 'cb_lat_pulldown',
    freeDbId: 'Wide-Grip_Lat_Pulldown',
    name: 'Lat pulldown',
    station: 'cable',
    attachment: 'lat_pulldown_bar',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upper_back', 'biceps', 'rear_delts', 'forearms'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'cb_seated_row',
    freeDbId: 'Seated_Cable_Rows',
    name: 'Seated row',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'cb_fly',
    freeDbId: 'Cable_Crossover',
    name: 'Cable fly',
    station: 'cable',
    attachment: 'single_arm',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'cb_straight_arm_pulldown',
    freeDbId: 'Straight-Arm_Pulldown',
    name: 'Straight-arm pulldown',
    station: 'cable',
    attachment: 'straight_curl_bar',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps', 'abs'],
    loadMultiplier: CABLE_BILATERAL,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
  },

  /* --- Landmine ---------------------------------------------------------- */
  /* The landmine loads the 20 kg Olympic bar, so barWeight is 20. Its lever
     geometry means the load at the handle is lower than the bar+plate total;
     that is not modelled in v1 and is worth revisiting if the numbers start
     looking odd next to the free-bar lifts. */
  {
    id: 'lm_press',
    name: 'Landmine press',
    station: 'landmine',
    attachment: 'landmine_handle',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['chest', 'triceps', 'abs'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'lm_row',
    name: 'Landmine row',
    station: 'landmine',
    attachment: 'landmine_handle',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delts', 'forearms'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'lm_rotation',
    name: 'Landmine rotation',
    station: 'landmine',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'front_delts'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'lm_squat_to_press',
    name: 'Landmine squat-to-press',
    station: 'landmine',
    primaryMuscles: ['quads', 'glutes', 'front_delts'],
    secondaryMuscles: ['abs', 'triceps', 'upper_back'],
    loadMultiplier: 1.0,
    barWeight: FREE_BAR_KG,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },

  /* --- Kettlebell -------------------------------------------------------- */
  {
    id: 'kb_swing',
    freeDbId: 'Two-Arm_Kettlebell_Swing',
    name: 'Swing',
    station: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'lats', 'traps', 'forearms', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: true,
  },
  {
    id: 'kb_goblet_squat',
    freeDbId: 'Goblet_Squat',
    name: 'Goblet squat',
    station: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs', 'upper_back', 'adductors'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'kb_single_leg_rdl',
    name: 'Single-leg RDL',
    station: 'kettlebell',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'abs', 'obliques', 'forearms'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: true,
  },
  {
    id: 'kb_turkish_get_up',
    freeDbId: 'Kettlebell_Turkish_Get-Up_(Squat_style)',
    name: 'Turkish get-up',
    station: 'kettlebell',
    primaryMuscles: ['abs', 'front_delts'],
    secondaryMuscles: ['obliques', 'glutes', 'triceps', 'quads'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'low',
    isHinge: false,
  },
  {
    id: 'kb_suitcase_carry',
    freeDbId: 'Farmers_Walk',
    name: 'Suitcase carry',
    station: 'kettlebell',
    primaryMuscles: ['forearms', 'obliques'],
    secondaryMuscles: ['traps', 'abs', 'glutes'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'high',
    isHinge: false,
  },

  /* --- Bodyweight -------------------------------------------------------- */
  {
    id: 'bw_pull_up',
    freeDbId: 'Pullups',
    name: 'Pull-up',
    station: 'bodyweight',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upper_back', 'biceps', 'forearms', 'rear_delts', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'bw_chin_up',
    freeDbId: 'Chin-Up',
    name: 'Chin-up',
    station: 'bodyweight',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upper_back', 'forearms', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'bw_dip',
    freeDbId: 'Dips_-_Triceps_Version',
    name: 'Dip',
    station: 'bodyweight',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['front_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'low',
    isHinge: false,
  },
  {
    id: 'bw_push_up',
    freeDbId: 'Pushups',
    name: 'Push-up',
    station: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bw_plank',
    freeDbId: 'Plank',
    name: 'Plank',
    station: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'front_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bw_side_plank',
    freeDbId: 'Side_Bridge',
    name: 'Side plank',
    station: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'side_delts'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bw_hanging_leg_raise',
    freeDbId: 'Hanging_Leg_Raise',
    name: 'Hanging leg raise',
    station: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'forearms', 'lats'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'high',
    isHinge: false,
  },
  {
    id: 'bw_split_squat',
    name: 'Split squat',
    station: 'bodyweight',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'abs'],
    loadMultiplier: 1.0,
    loadMode: 'weight',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bw_glute_bridge',
    name: 'Glute bridge',
    station: 'bodyweight',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back'],
    loadMultiplier: 1.0,
    loadMode: 'bodyweight',
    gripLoad: 'none',
    isHinge: false,
  },

  /* --- Bands (rpe_only — load is not quantifiable) ----------------------- */
  {
    id: 'bd_pull_apart',
    name: 'Band pull-apart',
    station: 'band',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back', 'traps'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'low',
    isHinge: false,
  },
  {
    id: 'bd_external_rotation',
    name: 'Band external rotation',
    station: 'band',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['side_delts'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: false,
  },
  {
    id: 'bd_pull_through',
    name: 'Band pull-through',
    station: 'band',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: true,
  },
  {
    id: 'bd_lateral_walk',
    name: 'Band lateral walk',
    station: 'band',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['adductors', 'quads'],
    loadMultiplier: 1.0,
    loadMode: 'rpe_only',
    gripLoad: 'none',
    isHinge: false,
  },
];

export const STATION_LABEL: Record<Exercise['station'], string> = {
  free_bar: 'Free bar',
  smith: 'Smith',
  cable: 'Cable',
  kettlebell: 'Kettlebell',
  bodyweight: 'Bodyweight',
  band: 'Band',
  landmine: 'Landmine',
};

/** Order stations the way the seed list is grouped, spec §8. */
export const STATION_ORDER: Exercise['station'][] = [
  'free_bar',
  'smith',
  'cable',
  'landmine',
  'kettlebell',
  'bodyweight',
  'band',
];
